"""add work orders table

Revision ID: 0ec5e270f3d9
Revises: f3a1c9d4b7e2
Create Date: 2026-09-02 02:49:03.059248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0ec5e270f3d9'
down_revision: Union[str, None] = 'f3a1c9d4b7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('series_configuration', sa.String(length=120), nullable=False),
    sa.Column('parallel_configuration', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=120), nullable=False),
    sa.Column('pack_barcode', sa.String(length=120), nullable=False),
    sa.Column('current_status', sa.String(length=120), nullable=False),
    sa.Column('actual_time', sa.DateTime(), nullable=True),
    sa.Column('completion_time', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_barcode', name='uq_work_order_pack_barcode')
    )
    op.create_index(op.f('ix_work_orders_batch_number'), 'work_orders', ['batch_number'], unique=False)
    op.create_index(op.f('ix_work_orders_pack_barcode'), 'work_orders', ['pack_barcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_pack_barcode'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_batch_number'), table_name='work_orders')
    op.drop_table('work_orders')
    # ### end Alembic commands ###
