"""initial schema

Revision ID: 1b6e7f24af91
Revises: 
Create Date: 2026-07-21 07:43:02.279551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1b6e7f24af91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('allowed_stations', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('auto_stacking_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('proline_code', sa.String(length=120), nullable=False),
    sa.Column('mod_code', sa.String(length=120), nullable=False),
    sa.Column('start_pressure', sa.Float(), nullable=False),
    sa.Column('end_pressure', sa.Float(), nullable=False),
    sa.Column('average_pressure', sa.Float(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mod_code', name='uq_auto_stacking_module')
    )
    op.create_index(op.f('ix_auto_stacking_readings_mod_code'), 'auto_stacking_readings', ['mod_code'], unique=False)
    op.create_table('cell_module_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('proline_code', sa.String(length=120), nullable=False),
    sa.Column('mod_code', sa.String(length=120), nullable=False),
    sa.Column('cell_code', sa.String(length=120), nullable=False),
    sa.Column('cell_index', sa.Integer(), nullable=False),
    sa.Column('station_code', sa.String(length=120), nullable=False),
    sa.Column('usercode', sa.String(length=120), nullable=False),
    sa.Column('employee_code', sa.String(length=120), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cell_code', name='uq_cell_module_binding_cell')
    )
    op.create_index(op.f('ix_cell_module_bindings_mod_code'), 'cell_module_bindings', ['mod_code'], unique=False)
    op.create_table('cell_sorting_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('proline_code', sa.String(length=120), nullable=False),
    sa.Column('cell_code', sa.String(length=120), nullable=False),
    sa.Column('station_code', sa.String(length=120), nullable=False),
    sa.Column('voltage', sa.Float(), nullable=False),
    sa.Column('inter_res', sa.Float(), nullable=False),
    sa.Column('nnr', sa.Float(), nullable=False),
    sa.Column('pass_information', sa.String(length=8), nullable=False),
    sa.Column('usercode', sa.String(length=120), nullable=False),
    sa.Column('employee_code', sa.String(length=120), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cell_code', 'station_code', name='uq_cell_sorting_cell_station')
    )
    op.create_index(op.f('ix_cell_sorting_readings_cell_code'), 'cell_sorting_readings', ['cell_code'], unique=False)
    op.create_table('laser_cleaning_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('station_code', sa.String(length=120), nullable=False),
    sa.Column('mod_code', sa.String(length=120), nullable=False),
    sa.Column('cell_coord', sa.String(length=120), nullable=False),
    sa.Column('cleaning_power', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('pass_information', sa.String(length=8), nullable=False),
    sa.Column('usercode', sa.String(length=120), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mod_code', 'cell_coord', name='uq_laser_cleaning_module_coord')
    )
    op.create_index(op.f('ix_laser_cleaning_readings_mod_code'), 'laser_cleaning_readings', ['mod_code'], unique=False)
    op.create_table('laser_welding_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('station_code', sa.String(length=120), nullable=False),
    sa.Column('mod_code', sa.String(length=120), nullable=False),
    sa.Column('cell_coord', sa.String(length=120), nullable=False),
    sa.Column('welding_power', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('pass_information', sa.String(length=8), nullable=False),
    sa.Column('usercode', sa.String(length=120), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mod_code', 'cell_coord', name='uq_laser_welding_module_coord')
    )
    op.create_index(op.f('ix_laser_welding_readings_mod_code'), 'laser_welding_readings', ['mod_code'], unique=False)
    op.create_table('liquid_cooling_airtightness_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('proline_code', sa.String(length=120), nullable=False),
    sa.Column('pack_code', sa.String(length=120), nullable=False),
    sa.Column('cooled_code', sa.String(length=120), nullable=False),
    sa.Column('chargetime', sa.Float(), nullable=False),
    sa.Column('holdtime', sa.Float(), nullable=False),
    sa.Column('testtime', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('leakage', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('station_code', sa.String(length=120), nullable=False),
    sa.Column('usercode', sa.String(length=120), nullable=False),
    sa.Column('employee_code', sa.String(length=120), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_code', name='uq_liquid_cooling_pack')
    )
    op.create_index(op.f('ix_liquid_cooling_airtightness_readings_pack_code'), 'liquid_cooling_airtightness_readings', ['pack_code'], unique=False)
    op.create_table('module_eol_test_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('station_code', sa.String(length=120), nullable=False),
    sa.Column('mod_code', sa.String(length=120), nullable=False),
    sa.Column('mod_V', sa.Float(), nullable=False),
    sa.Column('mod_V_Result', sa.String(length=8), nullable=False),
    sa.Column('mod_R', sa.Float(), nullable=False),
    sa.Column('mod_R_Result', sa.String(length=8), nullable=False),
    sa.Column('mod_IR', sa.Float(), nullable=False),
    sa.Column('mod_IR_Result', sa.String(length=8), nullable=False),
    sa.Column('mod_DWV', sa.Float(), nullable=False),
    sa.Column('mod_DWV_Result', sa.String(length=8), nullable=False),
    sa.Column('pass_information', sa.String(length=8), nullable=False),
    sa.Column('usercode', sa.String(length=120), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mod_code', name='uq_module_eol_module')
    )
    op.create_index(op.f('ix_module_eol_test_readings_mod_code'), 'module_eol_test_readings', ['mod_code'], unique=False)
    op.create_table('module_pack_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('proline_code', sa.String(length=120), nullable=False),
    sa.Column('mod_code', sa.String(length=120), nullable=False),
    sa.Column('pack_code', sa.String(length=120), nullable=False),
    sa.Column('mod_index', sa.Integer(), nullable=False),
    sa.Column('bms_code', sa.String(length=120), nullable=False),
    sa.Column('station_code', sa.String(length=120), nullable=False),
    sa.Column('usercode', sa.String(length=120), nullable=False),
    sa.Column('employee_code', sa.String(length=120), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mod_code', name='uq_module_pack_binding_module'),
    sa.UniqueConstraint('pack_code', 'mod_index', name='uq_module_pack_binding_pack_slot')
    )
    op.create_index(op.f('ix_module_pack_bindings_mod_code'), 'module_pack_bindings', ['mod_code'], unique=False)
    op.create_index(op.f('ix_module_pack_bindings_pack_code'), 'module_pack_bindings', ['pack_code'], unique=False)
    op.create_table('pack_airtightness_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('proline_code', sa.String(length=120), nullable=False),
    sa.Column('pack_code', sa.String(length=120), nullable=False),
    sa.Column('chargetime', sa.Float(), nullable=False),
    sa.Column('holdtime', sa.Float(), nullable=False),
    sa.Column('testtime', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('leakage', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('station_code', sa.String(length=120), nullable=False),
    sa.Column('usercode', sa.String(length=120), nullable=False),
    sa.Column('employee_code', sa.String(length=120), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_code', name='uq_pack_airtightness_pack')
    )
    op.create_index(op.f('ix_pack_airtightness_readings_pack_code'), 'pack_airtightness_readings', ['pack_code'], unique=False)
    op.create_table('pack_eol_test_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('station_code', sa.String(length=120), nullable=False),
    sa.Column('pack_code', sa.String(length=120), nullable=False),
    sa.Column('test_file_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pass_information', sa.String(length=8), nullable=False),
    sa.Column('usercode', sa.String(length=120), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_code', name='uq_pack_eol_pack')
    )
    op.create_index(op.f('ix_pack_eol_test_readings_pack_code'), 'pack_eol_test_readings', ['pack_code'], unique=False)
    op.create_table('polarity_detection_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('station_code', sa.String(length=120), nullable=False),
    sa.Column('mod_code', sa.String(length=120), nullable=False),
    sa.Column('col_coord', sa.String(length=120), nullable=False),
    sa.Column('mark_info', sa.String(length=255), nullable=False),
    sa.Column('pass_information', sa.String(length=8), nullable=False),
    sa.Column('usercode', sa.String(length=120), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mod_code', 'col_coord', name='uq_polarity_module_coord')
    )
    op.create_index(op.f('ix_polarity_detection_readings_mod_code'), 'polarity_detection_readings', ['mod_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_polarity_detection_readings_mod_code'), table_name='polarity_detection_readings')
    op.drop_table('polarity_detection_readings')
    op.drop_index(op.f('ix_pack_eol_test_readings_pack_code'), table_name='pack_eol_test_readings')
    op.drop_table('pack_eol_test_readings')
    op.drop_index(op.f('ix_pack_airtightness_readings_pack_code'), table_name='pack_airtightness_readings')
    op.drop_table('pack_airtightness_readings')
    op.drop_index(op.f('ix_module_pack_bindings_pack_code'), table_name='module_pack_bindings')
    op.drop_index(op.f('ix_module_pack_bindings_mod_code'), table_name='module_pack_bindings')
    op.drop_table('module_pack_bindings')
    op.drop_index(op.f('ix_module_eol_test_readings_mod_code'), table_name='module_eol_test_readings')
    op.drop_table('module_eol_test_readings')
    op.drop_index(op.f('ix_liquid_cooling_airtightness_readings_pack_code'), table_name='liquid_cooling_airtightness_readings')
    op.drop_table('liquid_cooling_airtightness_readings')
    op.drop_index(op.f('ix_laser_welding_readings_mod_code'), table_name='laser_welding_readings')
    op.drop_table('laser_welding_readings')
    op.drop_index(op.f('ix_laser_cleaning_readings_mod_code'), table_name='laser_cleaning_readings')
    op.drop_table('laser_cleaning_readings')
    op.drop_index(op.f('ix_cell_sorting_readings_cell_code'), table_name='cell_sorting_readings')
    op.drop_table('cell_sorting_readings')
    op.drop_index(op.f('ix_cell_module_bindings_mod_code'), table_name='cell_module_bindings')
    op.drop_table('cell_module_bindings')
    op.drop_index(op.f('ix_auto_stacking_readings_mod_code'), table_name='auto_stacking_readings')
    op.drop_table('auto_stacking_readings')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
