"""cell and module pass-gate columns

Revision ID: 5a8a51128be1
Revises: b6a59324b4a2
Create Date: 2026-07-21 08:09:43.021943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a8a51128be1'
down_revision: Union[str, None] = 'b6a59324b4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('pass_information', sa.String(length=8), nullable=False))
    op.add_column('modules', sa.Column('eol_pass_information', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'eol_pass_information')
    op.drop_column('cells', 'pass_information')
    # ### end Alembic commands ###
