"""add employee_code for traceability to 5 stations

Revision ID: 6c43a6a69c4e
Revises: 5a8a51128be1
Create Date: 2026-07-27 05:50:57.224213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c43a6a69c4e'
down_revision: Union[str, None] = '5a8a51128be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laser_cleaning_readings', sa.Column('employee_code', sa.String(length=120), nullable=True))
    op.add_column('laser_welding_readings', sa.Column('employee_code', sa.String(length=120), nullable=True))
    op.add_column('module_eol_test_readings', sa.Column('employee_code', sa.String(length=120), nullable=True))
    op.add_column('pack_eol_test_readings', sa.Column('employee_code', sa.String(length=120), nullable=True))
    op.add_column('polarity_detection_readings', sa.Column('employee_code', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polarity_detection_readings', 'employee_code')
    op.drop_column('pack_eol_test_readings', 'employee_code')
    op.drop_column('module_eol_test_readings', 'employee_code')
    op.drop_column('laser_welding_readings', 'employee_code')
    op.drop_column('laser_cleaning_readings', 'employee_code')
    # ### end Alembic commands ###
