"""add operators traceability table

Revision ID: 6ec7512308d9
Revises: 6c43a6a69c4e
Create Date: 2026-07-27 06:06:26.728762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ec7512308d9'
down_revision: Union[str, None] = '6c43a6a69c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operator_code', sa.String(length=120), nullable=False),
    sa.Column('operator_name', sa.String(length=120), nullable=True),
    sa.Column('first_station_code', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_operator_code'), 'operators', ['operator_code'], unique=True)
    op.create_index(op.f('ix_cell_module_bindings_usercode'), 'cell_module_bindings', ['usercode'], unique=False)
    op.create_foreign_key(None, 'cell_module_bindings', 'operators', ['usercode'], ['operator_code'])
    op.create_index(op.f('ix_cell_sorting_readings_usercode'), 'cell_sorting_readings', ['usercode'], unique=False)
    op.create_foreign_key(None, 'cell_sorting_readings', 'operators', ['usercode'], ['operator_code'])
    op.create_index(op.f('ix_laser_cleaning_readings_usercode'), 'laser_cleaning_readings', ['usercode'], unique=False)
    op.create_foreign_key(None, 'laser_cleaning_readings', 'operators', ['usercode'], ['operator_code'])
    op.create_index(op.f('ix_laser_welding_readings_usercode'), 'laser_welding_readings', ['usercode'], unique=False)
    op.create_foreign_key(None, 'laser_welding_readings', 'operators', ['usercode'], ['operator_code'])
    op.create_index(op.f('ix_liquid_cooling_airtightness_readings_usercode'), 'liquid_cooling_airtightness_readings', ['usercode'], unique=False)
    op.create_foreign_key(None, 'liquid_cooling_airtightness_readings', 'operators', ['usercode'], ['operator_code'])
    op.create_index(op.f('ix_module_eol_test_readings_usercode'), 'module_eol_test_readings', ['usercode'], unique=False)
    op.create_foreign_key(None, 'module_eol_test_readings', 'operators', ['usercode'], ['operator_code'])
    op.create_index(op.f('ix_module_pack_bindings_usercode'), 'module_pack_bindings', ['usercode'], unique=False)
    op.create_foreign_key(None, 'module_pack_bindings', 'operators', ['usercode'], ['operator_code'])
    op.create_index(op.f('ix_pack_airtightness_readings_usercode'), 'pack_airtightness_readings', ['usercode'], unique=False)
    op.create_foreign_key(None, 'pack_airtightness_readings', 'operators', ['usercode'], ['operator_code'])
    op.create_index(op.f('ix_pack_eol_test_readings_usercode'), 'pack_eol_test_readings', ['usercode'], unique=False)
    op.create_foreign_key(None, 'pack_eol_test_readings', 'operators', ['usercode'], ['operator_code'])
    op.create_index(op.f('ix_polarity_detection_readings_usercode'), 'polarity_detection_readings', ['usercode'], unique=False)
    op.create_foreign_key(None, 'polarity_detection_readings', 'operators', ['usercode'], ['operator_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'polarity_detection_readings', type_='foreignkey')
    op.drop_index(op.f('ix_polarity_detection_readings_usercode'), table_name='polarity_detection_readings')
    op.drop_constraint(None, 'pack_eol_test_readings', type_='foreignkey')
    op.drop_index(op.f('ix_pack_eol_test_readings_usercode'), table_name='pack_eol_test_readings')
    op.drop_constraint(None, 'pack_airtightness_readings', type_='foreignkey')
    op.drop_index(op.f('ix_pack_airtightness_readings_usercode'), table_name='pack_airtightness_readings')
    op.drop_constraint(None, 'module_pack_bindings', type_='foreignkey')
    op.drop_index(op.f('ix_module_pack_bindings_usercode'), table_name='module_pack_bindings')
    op.drop_constraint(None, 'module_eol_test_readings', type_='foreignkey')
    op.drop_index(op.f('ix_module_eol_test_readings_usercode'), table_name='module_eol_test_readings')
    op.drop_constraint(None, 'liquid_cooling_airtightness_readings', type_='foreignkey')
    op.drop_index(op.f('ix_liquid_cooling_airtightness_readings_usercode'), table_name='liquid_cooling_airtightness_readings')
    op.drop_constraint(None, 'laser_welding_readings', type_='foreignkey')
    op.drop_index(op.f('ix_laser_welding_readings_usercode'), table_name='laser_welding_readings')
    op.drop_constraint(None, 'laser_cleaning_readings', type_='foreignkey')
    op.drop_index(op.f('ix_laser_cleaning_readings_usercode'), table_name='laser_cleaning_readings')
    op.drop_constraint(None, 'cell_sorting_readings', type_='foreignkey')
    op.drop_index(op.f('ix_cell_sorting_readings_usercode'), table_name='cell_sorting_readings')
    op.drop_constraint(None, 'cell_module_bindings', type_='foreignkey')
    op.drop_index(op.f('ix_cell_module_bindings_usercode'), table_name='cell_module_bindings')
    op.drop_index(op.f('ix_operators_operator_code'), table_name='operators')
    op.drop_table('operators')
    # ### end Alembic commands ###
