"""add work_order_id to work orders

Revision ID: aa729e7de9da
Revises: 0ec5e270f3d9
Create Date: 2026-09-02 03:05:49.275195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa729e7de9da'
down_revision: Union[str, None] = '0ec5e270f3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('work_order_id', sa.String(length=120), nullable=False))
    op.create_index(op.f('ix_work_orders_work_order_id'), 'work_orders', ['work_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_work_order_id'), table_name='work_orders')
    op.drop_column('work_orders', 'work_order_id')
    # ### end Alembic commands ###
