"""genealogy tables and referential fks

Revision ID: b6a59324b4a2
Revises: 1b6e7f24af91
Create Date: 2026-07-21 08:01:58.410852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b6a59324b4a2'
down_revision: Union[str, None] = '1b6e7f24af91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cell_code', sa.String(length=120), nullable=False),
    sa.Column('proline_code', sa.String(length=120), nullable=False),
    sa.Column('first_station_code', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cells_cell_code'), 'cells', ['cell_code'], unique=True)
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mod_code', sa.String(length=120), nullable=False),
    sa.Column('proline_code', sa.String(length=120), nullable=False),
    sa.Column('first_station_code', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_mod_code'), 'modules', ['mod_code'], unique=True)
    op.create_table('packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pack_code', sa.String(length=120), nullable=False),
    sa.Column('proline_code', sa.String(length=120), nullable=False),
    sa.Column('first_station_code', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packs_pack_code'), 'packs', ['pack_code'], unique=True)
    op.create_foreign_key(None, 'auto_stacking_readings', 'modules', ['mod_code'], ['mod_code'])
    op.create_foreign_key(None, 'cell_module_bindings', 'cells', ['cell_code'], ['cell_code'])
    op.create_foreign_key(None, 'cell_module_bindings', 'modules', ['mod_code'], ['mod_code'])
    op.create_foreign_key(None, 'cell_sorting_readings', 'cells', ['cell_code'], ['cell_code'])
    op.create_foreign_key(None, 'laser_cleaning_readings', 'modules', ['mod_code'], ['mod_code'])
    op.create_foreign_key(None, 'laser_welding_readings', 'modules', ['mod_code'], ['mod_code'])
    op.create_foreign_key(None, 'liquid_cooling_airtightness_readings', 'packs', ['pack_code'], ['pack_code'])
    op.create_foreign_key(None, 'module_eol_test_readings', 'modules', ['mod_code'], ['mod_code'])
    op.create_foreign_key(None, 'module_pack_bindings', 'packs', ['pack_code'], ['pack_code'])
    op.create_foreign_key(None, 'module_pack_bindings', 'modules', ['mod_code'], ['mod_code'])
    op.create_foreign_key(None, 'pack_airtightness_readings', 'packs', ['pack_code'], ['pack_code'])
    op.create_foreign_key(None, 'pack_eol_test_readings', 'packs', ['pack_code'], ['pack_code'])
    op.create_foreign_key(None, 'polarity_detection_readings', 'modules', ['mod_code'], ['mod_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'polarity_detection_readings', type_='foreignkey')
    op.drop_constraint(None, 'pack_eol_test_readings', type_='foreignkey')
    op.drop_constraint(None, 'pack_airtightness_readings', type_='foreignkey')
    op.drop_constraint(None, 'module_pack_bindings', type_='foreignkey')
    op.drop_constraint(None, 'module_pack_bindings', type_='foreignkey')
    op.drop_constraint(None, 'module_eol_test_readings', type_='foreignkey')
    op.drop_constraint(None, 'liquid_cooling_airtightness_readings', type_='foreignkey')
    op.drop_constraint(None, 'laser_welding_readings', type_='foreignkey')
    op.drop_constraint(None, 'laser_cleaning_readings', type_='foreignkey')
    op.drop_constraint(None, 'cell_sorting_readings', type_='foreignkey')
    op.drop_constraint(None, 'cell_module_bindings', type_='foreignkey')
    op.drop_constraint(None, 'cell_module_bindings', type_='foreignkey')
    op.drop_constraint(None, 'auto_stacking_readings', type_='foreignkey')
    op.drop_index(op.f('ix_packs_pack_code'), table_name='packs')
    op.drop_table('packs')
    op.drop_index(op.f('ix_modules_mod_code'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_cells_cell_code'), table_name='cells')
    op.drop_table('cells')
    # ### end Alembic commands ###
